name = "pastebin-worker"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

account_id = "0d97d5e5babb1cf09223c5ee027337b5"
main = "src/index.ts"
workers_dev = false

[vars]
ENVIRONMENT = "production"
BASE_URL = "https://ydev.tech"

[site]
bucket = "./static/dist"

# 如果不使用自定义域名，将下面的代码注释掉
[[routes]]
pattern = "ydev.tech"
custom_domain = true

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'pastes'

[[d1_databases]]
binding = "DB"
database_name = "paste"
database_id = "f6cfeb95-5eec-433b-b923-7d7f55eef9ba"
