name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Yarn
        run: npm i -g yarn

      - name: Build frontend
        run: cd static && yarn install && yarn build

      - name: Install Dependencies
        run: yarn install

      - name: Publish
        uses: cloudflare/wrangler-action@3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        env:
            NO_D1_WARNING: true
